### PR TITLE
Ignore EBADF error

### PR DESCRIPTION
**Pull request by christianbundy**
This ignores the EBADF errors that are being thrown constantly.

I think that bug should be tracked in https://github.com/pull-stream/pull-file/issues/6, but I'd like to reduce the number of errors being logged since they seem to be harmless.

I've also removed the `write()` function above, since it isn't used anywhere.

### CODE REVIEW

**Review by staltz — APPROVED** [review]

**Comment by christianbundy** [comment]
Thank you!

**Comment by dominictarr** [comment]
What does this do on an ENOENT? does it just return an empty stream? ENOENT is an important error. multiblob is a low level library, if ssb has too many errors, ignoring them here isn't the right place. Ignore them in ssb-blobs ;)

**Comment by staltz** [comment]
@dominictarr Prior to the PR it was ignoring ENOENT already, right?

**Comment by dominictarr** [comment]
it seems that was only added recently, I'm a bit confused because it's all in a massive merge commit: https://github.com/ssbc/multiblob/commit/81803a9de0e96476136cb7a2dab21f54f59ae592#diff-168726dbe96b3ce427e7fedce31bb0bc looks like it was direct to the master branch? doesn't seem to be a part of a PR from what I can see? 17 days ago.

The git blame before that shows it had been using pull-file without ignoring anything for 4 years.
https://github.com/ssbc/multiblob/blame/bed60ce174e86f1bca13d52a28780e9e09d33876/index.js

**Comment by staltz** [comment]
Hmm, honestly I have little idea why is this ignore code here in the first place. I just assumed that it's okay to add one more error check if there has been already been other error checks before. The fact that I pressed 'approve' is also not necessarily a strong vote to merge it.

Overall I agree that low level libraries should bubble errors up, and high level libraries should make opinionated filters.

**Comment by dominictarr** [comment]
aside: @staltz to be honest, I hate the "approve" button. pressing a button is the easiest thing in the world. writing a sentence "LGTM" "this seems like a good idea" "I'm keen to use this feature" "this problem has been annoying me" etc carries so much more meaning and gives at least a little insight into how much effort the reviewer put into understanding the code. The Approve button has no subtext!

**Comment by christianbundy** [comment]
I think this *is* supposed to bubble up the errors, we're just passing the error through the stream instead of crashing the stream or logging to stdout. The `ignoredErrorCodes` array is only checked for the `console.error()` side-effect, not for the error handling itself.

**Comment by christianbundy** [comment]
Also, adding a data point, I really like the 'approve' button. It's very common for me to open a PR, receive a reply, and be confused about what the reply is saying.

- Are they requesting changes?
- Do they want me to merge?
- Are they saying they're excited for the feature but haven't looked at the code?
- Are they just sharing an interesting thought or anecdote?

Having an explicit *I am approving this pull request to be merged* button works to reduce this confusion, but I suppose that doesn't work very well if:

> The fact that I pressed 'approve' is also not necessarily a strong vote to merge it.

Regardless, I agree that a merge approval should have some text explaining it.

Zooming out a bit, I think it would be beneficial to be more explicit about how things get merged in the SSBC. Here's the workflow I've been using:

1. Alice opens a PR
2. Bob requests changes
3. Alice makes changes
4. Bob approves
5. Alice clicks 'merge' and publishes a new version

I think there's another common pattern that others have:

1. Alice opens a PR
2. Bob requests changes
3. Alice makes changes
4. Bob clicks 'merge' and publishes a new version

We have a [long backlog of PRs awaiting review](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Assbc+archived%3Afalse+sort%3Aupdated-asc+-repo%3Assbc%2Fssb-server+-repo%3Assbc%2Fpatchwork+-repo%3Assbc%2Fpatchbay+) and it's difficult to get reviews, so I'm personally inclined to keep Bob's job as small as possible.

**Comment by dominictarr** [comment]
bubbling up errors would cause even more surprises than just ending the stream normally!
but thankfully this is what `pull-catch`'s readme says:

> This is a through stream that can ensure your source stream always ends normally, even when it returns an error. This is useful if you are combining several source streams with pull-many, and you want to keep the remaining streams open even if one of them errors.

merge/pr workflow discussions aside, I still don't quite understand how this came to ignore ENOENT,

okay making progress... https://github.com/ssbc/multiblob/commit/030c6a5c68b327020099951e904c17aa230d260a

**Comment by dominictarr** [comment]
Oh, it's not actually ignoring the errors. it's passing them normally, it's just _not logging_ errors that are ENOENT or EBADF, all errors are still normal. Also, it's redacting all error messages to avoid leaking any private information about the file system.

**Comment by dominictarr** [comment]
okay, so when I saw the code and it said "ignoring errors" I got alarmed but it's actually just the code was misleading, the only thing that is ignoring errors is the `console.log`... if this issue wasn't already closed I would close it now!

**Pull request merged**
