### PR TITLE
Redact sensitive information from pull-file error

### LINKED ISSUE #877: blobs.get non-existent blob ENOENT leaks local $HOME dir and username in error message
because blobs are stored in $HOME/.ssb/blobs, when we get an ENOENT and return an error message, it leaks the username of the user's $HOME dir

`'message': "ENOENT: no such file or directory, open '/Users/XXX/.ssb/blobs/sha256/ff/aabb24e2b2b618279f3a01239c71be8b42af91de16400865202ea878997cbc'`
```
INFO:packet_stream - SEND [1]: <PSMessage (JSON): {'name': ['blobs', 'get'], 'args': ['&/6q7JOKythgnnzoBI5xxvotCr5HeFkAIZSAuqHiZfLw=.sha256'], 'type': 'source'} [1] ~>
INFO:packet_stream - RESPONSE [1]: <PSMessage (JSON): {'message': "ENOENT: no such file or directory, open '/Users/XXX/.ssb/blobs/sha256/ff/aabb24e2b2b618279f3a01239c71be8b42af91de16400865202ea878997cbc'", 'name': 'Error', 'stack': "Error: ENOENT: no such file or directory, open '/Users/XXX/.ssb/blobs/sha256/ff/aabb24e2b2b618279f3a01239c71be8b42af91de16400865202ea878997cbc'"} [-1] ~!>
IN
```

### PR DESCRIPTION
**Pull request by christianbundy**
Resolves https://github.com/ssbc/patchwork/issues/877.

## Before

```json
{
  "message": "ENOENT: no such file or directory, open '/home/christianbundy/.ssb/blobs/sha256/ff/aabb24e2b2b618279f3a01239c71be8b42af91de16400865202ea878997cbc'",
  "name": "Error",
  "stack": "Error: ENOENT: no such file or directory, open '/home/christianbundy/.ssb/blobs/sha256/ff/aabb24e2b2b618279f3a01239c71be8b42af91de16400865202ea878997cbc'"
}
```

## After

```json
{
  "message": "could not get blob",
  "name": "Error",
  "stack": "Error: could not get blob"
}
```

### CODE REVIEW

**Comment by cryptix** [comment]
LGTM! concise change of the one `read` function.

future work could be inspecting the error in the catch. For instance I'd like to get a `console.error` from my sbot if reading the file got a permission error (like in a incomplete move between installation/locations as root, forgetting chmod for instance). _Later_ because I don't think it should block this but _might_ be a doozy if it just get's ignored/dropped.

**Comment by christianbundy** [comment]
Thanks! Do you think this would be improved by adding a `console.trace` with the real error if it's something other than ENOENT? Or a `debug`? Or throwing an actual error, given the assumption that it won't crash sbot.

**Comment by cryptix** [comment]
+1 on everything besides ENOENT getting elevated.

I'd use the logging plugin that we have. I'm not sure if those should be `warning` but I'm leading towards `error` because everything else but ENOENT _should_ work, in my book.

-1 on `console.trace` since it's very verbose on the log and I think it _should_ only be used in very rare cases where you don't know where it is coming from. Also -1 to `throw` because it could crash pubs if it goes uncatched.

**Comment by christianbundy** [comment]
Thanks for the feedback, I think that's a really good idea. Now, when the file access fails for any reason except ENOENT the user will get the error [privately] logged like [this](https://asciinema.org/a/6OBasyrJJ4O3drh8J4BsMNKP6):

> Error: EACCES: permission denied, open '/home/christianbundy/.ssb/blobs/sha256/ff/aabb24e2b2b618279f3a01239c71be8b42af91de16400865202ea878997cbc'
 
Anything else look funky?

**Comment by dominictarr** [comment]
@christianbundy it's good that it changes the message, but I think it should keep the stack in this place. It's muxrpc that should discard the stack - as that is the point this becomes a privacy problem. discarding the stack for everything makes things somewhat hard to debug.

**Comment by christianbundy** [comment]
Thanks @dominictarr. I just pushed a new commit with that change. I made an attempt to make this change with [this PR](https://github.com/ssbc/muxrpc/pull/42), but it didn't work how I expected and I couldn't get a feel for how far off I was.

**Comment by christianbundy** [comment]
Anyone else see anything concerning in this branch? Otherwise, I'll likely merge and publish this tomorrow.

**Comment by dominictarr** [comment]
@christianbundy :+1:

**Comment by dominictarr** [comment]
fixed in 1.13.7

**Pull request merged**
