### PR TITLE
Replace "ignored" with "silenced" for clarity

### PR DESCRIPTION
**Pull request by christianbundy**
https://github.com/ssbc/multiblob/pull/14#issuecomment-563774998 

Someone having a bad time sounds like a bug to me. Recommendations welcome.

### CODE REVIEW

**Comment by dominictarr** [comment]
why not just drop the error logging altogether? why is that even there?

I did some digging: https://github.com/ssbc/multiblob/pull/9
the PR was just about redacting private stuff, but then @cryptix suggests logging the message, incase his permissions where set up wrong and nothing can read the blobs. https://github.com/ssbc/multiblob/pull/9#issuecomment-438950543

If the ssb server process doesn't have read access to `.ssb/*` then loads of other things will have fatal errors, you won't be able to read the config file, or log, or views... blobs is one thing that wouldn't fail on start up, but it seems unlikely to me that we'd only get an access problem in the blobs dir, and not the others.

**Comment by christianbundy** [comment]
That works for me, I'd love to avoid CLI error output from low-level libraries. What do you think @cryptix?

**Comment by cryptix** [comment]
Sure, dropping it all together SGTM, too.

IIRC issue 9 was about leaking the error over muxrpc to remote peers. I feel like local logging should be informative enough to whoever runs the system so only made the initial suggestion to help debugging but yes, only blobs being inaccessable sounds far fetched.

**Comment by dominictarr** [comment]
fixed in 1.13.7

**Pull request closed without merging**
